pr:
- master
- development

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'

- script: npm install
  displayName: 'Lining up turtle friends'

- script: npm run lint
  displayName: 'Checking appearance of the turtle'

- script: npm run test
  displayName: 'Checking behaviour of the turtle'

- script: npm run build
  displayName: 'Checking health of the turtle'

# Possibly some db migration via webpack?
