enum NOTIFICATIONS {
  CONNECTION_REQUEST = 'connectionRequest',
  CONNECTION_APPROVAL = 'connectionApproval',
  HOUSEHOLD_INVITATION = 'householdInvitation',
  HOUSEHOLD_JOINING = 'householdJoining',
  HOUSEHOLD_LEAVING = 'householdLeaving',
  HOUSEHOLD_DELETING = 'householdDeleting',
  HOUSEHOLD_EXPELLING = 'householdExpelling',
}

const NOTIFICATION_EMAILS: Record<NOTIFICATIONS, string> = {
  [NOTIFICATIONS.CONNECTION_REQUEST]: '',
  [NOTIFICATIONS.CONNECTION_APPROVAL]: '',
  [NOTIFICATIONS.HOUSEHOLD_INVITATION]: '',
  [NOTIFICATIONS.HOUSEHOLD_JOINING]: '',
  [NOTIFICATIONS.HOUSEHOLD_LEAVING]: '',
  [NOTIFICATIONS.HOUSEHOLD_DELETING]: '',
  [NOTIFICATIONS.HOUSEHOLD_EXPELLING]: '',
}

export { NOTIFICATIONS, NOTIFICATION_EMAILS }
