export const PASSWORD = 'password'
export const TEXT = 'text'
export const TEXT_AREA = 'text-area'
export const EMAIL = 'email'
export const PHOTO = 'photo'
export const FILE = 'file'
export const BOOL = 'bool'
export const SWITCH = 'switch'
