export const SETTING_COLUMNS = {
  CATEGORY: 'category',
  TAB: 'tab',
}

export const SETTING_CATEGORIES = {
  PROFILE: 'profile',
  CONNECTIONS: 'connections',
  HOUSEHOLDS: 'households',
}

export const SETTING_TABS = {
  GENERAL: 'general',
  NOTIFICATIONS: 'notifications',

  MY_CONNECTIONS: 'myConnections',
  FIND_CONNECTION: 'findConnection',
  PENDING: 'pending',
  BLOCKED: 'blocked',

  NEW_HOUSEHOLD: 'newHousehold',
  INVITATIONS: 'invitations',
  _HOUSEHOLD: 'household',
}

export const SETTING_TAB_ROWS = {
  [SETTING_CATEGORIES.PROFILE]: [SETTING_TABS.GENERAL, SETTING_TABS.NOTIFICATIONS],
  [SETTING_CATEGORIES.CONNECTIONS]: [
    SETTING_TABS.MY_CONNECTIONS, SETTING_TABS.FIND_CONNECTION, SETTING_TABS.PENDING, SETTING_TABS.BLOCKED,
  ],
  [SETTING_CATEGORIES.HOUSEHOLDS]: [SETTING_TABS.INVITATIONS, SETTING_TABS.NEW_HOUSEHOLD],
  'new-category': [SETTING_TABS.GENERAL],
}
