import { NotifySettingsApiType } from 'api/database/mappers'

enum NOTIFICATION {
  CONNECTION_REQUEST = 'CONNECTION_REQUEST',
  CONNECTION_APPROVAL = 'CONNECTION_APPROVAL',
  HOUSEHOLD_INVITATION = 'HOUSEHOLD_INVITATION',
  HOUSEHOLD_JOINING = 'HOUSEHOLD_JOINING',
  HOUSEHOLD_LEAVING = 'HOUSEHOLD_LEAVING',
  HOUSEHOLD_DELETING = 'HOUSEHOLD_DELETING',
  HOUSEHOLD_REMOVAL = 'HOUSEHOLD_REMOVAL',
  HOUSEHOLD_REMOVAL_MULTIPLE = 'HOUSEHOLD_REMOVAL_MULTIPLE',
}

export const NOTIFICATION_KEYS: Record<NOTIFICATION, keyof NotifySettingsApiType> = {
  HOUSEHOLD_REMOVAL: 'householdExpelling',
  HOUSEHOLD_REMOVAL_MULTIPLE: 'householdExpelling',
  HOUSEHOLD_INVITATION: 'householdInvitation',
  HOUSEHOLD_DELETING: 'householdDeleting',
  HOUSEHOLD_LEAVING: 'householdLeaving',
  HOUSEHOLD_JOINING: 'householdJoining',
  CONNECTION_REQUEST: 'connectionRequest',
  CONNECTION_APPROVAL: 'connectionApproval',
}
