on:
  push:
    branches: deployment-fix # Change to development after fix

env:
  AZURE_WEBAPP_NAME: household-chores-beta
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '12.x'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Branch'
      uses: actions/checkout@v2

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: 'npm install, build, and test'
      run: |
        npm install
        # npm run migrate up # allow after db set-up
        npm run build
        rm -rf ./node_modules
        npm install --production
        echo "Test test"
        echo ""/home/site/wwwroot/node_modules/ts-node/dist/bin.js"" > ./node_modules/.bin/ts-node
        echo "bla" > ./test.txt

    - name: 'Deploy to Azure Beta WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_BETA_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
