name: PR Testing Pipeline

on:
  pull_request:
    branches: [ development, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    # Eslint
    - run: npm run lint
    # Build
    - run: npm run build
    # Mocha
    - run: npm run test
